create-arch-sdcard-image: Add check for MacOS and exit if true
There are many tools used by this script that don't exist/are different
in MacOS, for example: getopt, fallocate, losetup, mkfs. Adding support
for MacOS is not trivial and not worth it at the moment, so we just
exit.

diff --git a/raspberry-pi/create-arch-sdcard-image b/raspberry-pi/create-arch-sdcard-image
--- a/raspberry-pi/create-arch-sdcard-image
+++ b/raspberry-pi/create-arch-sdcard-image
@@ -258,6 +258,16 @@ Options
         (see above)."
 }
 
+# Preliminary sanity checks
+if [ "$(uname)" = "Darwin" ]; then
+    log "Error: MacOS is not supported, use Linux or a Linux Virtual Machine"
+    exit 1
+fi
+if [ "${EUID}" != 0 ]; then
+    log "Error: you must be root"
+    exit 1
+fi
+
 if ! options=$(getopt \
                 --options "hH:k:p:s:w:" \
                 --longoptions \
@@ -302,12 +312,6 @@ while true; do
             ;;
     esac
 done
-
-# Sanity checks
-if [ "${EUID}" != 0 ]; then
-    log "Error: you must be root"
-    exit 1
-fi
 
 dest=${1:-}
 if [ -z "${dest}" ]; then
